### ISSUE TITLE
create a freemium option for 3 months

### ISSUE THREAD

**Issue by waleedhammam** [threefoldfoundation/www_owncloud#1]
### option 1 (current option)

- Create a website for users to login with threefold connect.
- This will take the 3Bot name and wallet address and send fund request to support.
- Support decide to transfer TFTs to user's wallet address with amount enough for 3 months

  ### checks
  
  - user only request once
  - only support admins can see the registered requests.
  - tfts amount is calculated on the spec of 8 core cpu, 8GB ram, 100GB disk
 
  ### Concerns
  
  - user can take the tfts and don't deploy the owncloud
  - payment can differ according to traffic ?

**Comment by waleedhammam** [comment]
The deployment costs 3050 TFT for 3 months for spec (8CPU, 8GB Ram, 100GB Disk)
so 30,5M TFT for 10K deployments

**Comment by waleedhammam** [comment]
POC for option 1
package lives here: https://github.com/waleedhammam/facuet
and deployed on: https://waleed.threefold.io/faucet/
and results at: https://waleed.threefold.io/faucet/api/result/get

![IMG_20220124_113230_811](https://user-images.githubusercontent.com/10658229/150757707-e01ac19c-722c-4d1f-acd1-1e18ecf92486.jpg)
![IMG_20220124_113233_023](https://user-images.githubusercontent.com/10658229/150757712-9801d337-5f4d-43b6-b051-4017ac91aeb0.jpg)
![IMG_20220124_113235_512](https://user-images.githubusercontent.com/10658229/150757717-bdbaf66e-a71c-4366-b334-9f2df2358719.jpg)
![IMG_20220124_113237_036](https://user-images.githubusercontent.com/10658229/150757720-eb71e1e1-e84e-4806-aa34-2cb017354ae7.jpg)

**Comment by waleedhammam** [comment]
## Option 2

- Create a central point to deploy owncloud and give domain to user

## Concerns 

- To deploy this number we will need more than twin (at least 5) that will be difficult to monitor and needs 5 wallets to be funded. (if 5 twins will need almost 6 days to finish deployments)
- All workloads can be deleted if wallets ran out of funds. 
- Network traffic (NU) can accelerate wallet draining if users abuse the usage.
- Support will be difficult for such number of deployments.
- A lot of things can go wrong of managing this number of deployments.
- Users don't own the solution so it'll be deleted after 3 months and can cause data loss

**Comment by weynandkuijpers** [comment]
Discussing the concerns:

Q: To deploy this number we will need more than twin (at least 5) that will be difficult to monitor and needs 5 wallets to be funded. (if 5 twins will need almost 6 days to finish deployments)

*This will be an organically growing number of users that will be attracted through marketing and communication campaigns.  I do not expect we will be doing 100's of new account a day therefore the volume of deployments throughput is manageable.  Monitoring wallets must not be a bottleneck. We should be able to have (simple) automation and monitoring around this that start sending warnings at a certain (low) level of funds available in these wallets.*

Q: All workloads can be deleted if wallets ran out of funds.

*As above, proper monitoring should mitigate this risk.  Secondly we can create terms and conditions that make us not liable in case this happens as it is a freebe.  We must stipulate that we expect people to make regular backups of there data and configurations.*

Q: Network traffic (NU) can accelerate wallet draining if users abuse the usage.

*One important aspect / detail here is that we will use known farms and farmers.  These farmers have operational capabilities to monitor and mitigate the wallets draining.*

Q: Support will be difficult for such number of deployments.

*We will build a support model together with these known farmers and sales channels.  They will actively be part of the support process.  We are considering (and they have responded positive) GreenEdge.*


Q: A lot of things can go wrong of managing this number of deployments.
    Users don't own the solution so it'll be deleted after 3 months and can cause data loss

*The purpose is to attract users with the freemium that will want to continue the service after the freemium period is over.  So we will have to think (during the freemium period) how we convert them to a paying account.  More importantly we would want to hand over this freemium platform to these partners (farmers / sale channel) for them to take it forward and convert users to paying users, support them, monitor them.  So we are kickstarting it but then they will take over.*

**Comment by sameh-farouk** [comment]
after discussing with @waleedhammam and @rkhamis, we have in mind this flow where the users:
1- go to the website to request the Owncloud free instance by login in using his TF-connect where the request is recorded with the 3bot name and email address for each user. and it will give the users the option to choose a different email address where it will receive the deployment info/credentials. also, users will have to accept the terms and conditions before applying. 
2- the support team uses a specially authorized dashboard to check/approve the requests in patches.
3- on request approval, we will use terraform in the backend to deploy the requested instances by providing the 3bot names, which will be used in the instances domains.
4- it will retry to apply the infrastructures till reaching a specific threshold, if the deployment failed it will clean up the deployments then send an email to support with a report in case of success or failure, and to the users with the deployment info only if succeeded.
5- in the dashboard, we mark every request with the deployment status (new/pending/done/failed) and the support team can retry to redeploy the failed instances.
## Notes:
- all deployments will be funded from one preconfigured big wallet/account
- we will keep all deployments states in separated directories based on the date/time created.

**Comment by waleedhammam** [comment]
**Current progress**

- Add the structure for backend models and endpoints [in this repo](https://github.com/waleedhammam/facuet/tree/main/faucet)
- @ehab-hassan and @samaradel are working on the UI using vue for submission and dashboard pages
- @sameh-farouk is working on checking and adapting terraform python client.
- @waleedhammam is working on checking and adapting tf-chain python client

**Needs**
- Terms and conditions

**Comment by waleedhammam** [comment]
## Current Status

### First full version is now available

![image](https://user-images.githubusercontent.com/10658229/152024252-ebada6ca-342e-4d02-a841-f42db2248fe5.png)

![image](https://user-images.githubusercontent.com/10658229/152024262-7892848a-8f99-471b-9324-99e438e2717e.png)

![image](https://user-images.githubusercontent.com/10658229/152024286-fae6d144-5e3c-4cf9-8bcb-0bf878947e50.png)

![image](https://user-images.githubusercontent.com/10658229/152024269-3755c56f-a458-4b60-b0a2-6866a7f16017.png)

![image](https://user-images.githubusercontent.com/10658229/152024294-f29177e9-8c67-41ee-aa91-b06c48b9b870.png)

![image](https://user-images.githubusercontent.com/10658229/152024313-fde23ffa-4bef-412e-b225-28ce05e5db25.png)

![image](https://user-images.githubusercontent.com/10658229/152024323-3d3b5619-6674-4a12-b360-b34a81d68a6b.png)

### TODO

- Finalize UI
- Terms and conditions
- Dockerfile
- Testing

**Comment by weynandkuijpers** [comment]
For term and conditions let's use these as the starting point.  There have to be made some adaptions but this is a good starting point: https://owncloud.online/terms/

Also take the terms and conditions that are o be accepted before the TF Connect / when you get your twin in the portal.grid.tf.

**Comment by weynandkuijpers** [comment]
@waleedhammam Can I deploy / experience the current version somewhere?

**Comment by weynandkuijpers** [comment]
Also some additional requirements for the deployments:
- [ ] compute and storage sizing.  This should be a simple select button in the provisioning portal.
 - small (button)
   - [ ] CRU = 0.1
   - [ ] MRU = 0.5
   - [ ] SRU = 50
   - [ ] HRU = 0
   - [ ] Duration: 3 months
 - medium (button)
   - [ ] CRU = 0.5
   - [ ] MRU = 2.0
   - [ ] SRU = 100
   - [ ] HRU = 0
   - [ ] Duration: 2 months
 - large (button)
   - [ ] CRU = 2
   - [ ] MRU = 4
   - [ ] SRU = 150
   - [ ] HRU = 0
   - [ ] Duration: 1 month
- [ ] data backup structure
    - [ ]  data backup should copy the data from the private and individual SSSD based volume to a central QSS based storage/archive volume.  Looking at the datasizes this should and could be a large scale test for the QSS storage facility
    - [ ]  Process:
      - [ ]  mount volume (SSD) for active data store of Owncloud to the individual Owncloud VM
      - [ ] mount QSS volume on the Owncloud VM
      - [ ] use restic to make a backup of the active SSD storage space on the QSS storage volume
      - [ ] use a different directory per Owncloud VM.

**Comment by sasha-astiadi** [comment]
will this website be live for everyone on 1 public domain, or does user need to first deploy owncloud from play.grid.tf to access this website? @waleedhammam  Whats the userflow here to get 3 months freemium?

**Comment by rkhamis** [comment]
there will be a deployer (one) where users can request an owncloud instance.

ops would then have a dashboard where they can verify that these requests are made by valid users. once verified, deployments are made and each user gets an email with the deployment details

**Comment by sasha-astiadi** [comment]
so this www_owncloud is an owncloud deployer? what domain will it be used for the deployer?
why cant we do it on play.grid.tf instead of making another deployer? @rkhamis

**Comment by rkhamis** [comment]
> why cant we do it on play.grid.tf instead of making another deployer?

because it's going to be deployed from our wallet, not clients'. and it also allows us to accept requests and verifying that they're part of the freemium plan

**Comment by waleedhammam** [comment]
## Current progress

### Implemented an alpha version, demo below. Contains the following

- Destroy service: iterates over deployed instances and destroy them after the trial is over
- Front-end improvements
- Implementing locking mechanism between services
- Bug fixes and improvments

### To-Do

- [x] Improve texts and email content
- [x] Unit-tests clients for terraform python client. + option for lockfile removal in client
- [x] Create Dockerfile to make it easy to build
- [x] Documentation of the package and components.
- [x] Service to automatic re-deploy failures.

### Demo

available at: https://waleed.threefold.io

https://user-images.githubusercontent.com/10658229/152363335-c1716b62-32c2-47d2-896d-b85785ff4f49.mp4

**Comment by waleedhammam** [comment]
deployed and demo on waleed.threefold.io
